### ISSUE TITLE
Model initialization fails with Python 3.8.0

### ISSUE THREAD

**Issue by arodav** [bambinos/bambi#387]
Hi,
I'm not able to initialize an instance of `Model()` in the virtual environment I'm currently using:
```
Last updated: Tue Aug 03 2021

Python implementation: CPython
Python version       : 3.8.0
IPython version      : 7.26.0

matplotlib: 3.4.2
numpy     : 1.21.1
arviz     : 0.11.2
[GCC 8.4.0]
bambi     : 0.5.0
pandas    : 1.3.1

Watermark: 2.2.0
```
When initializing the instance, I get this error:
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/tmp/ipykernel_17456/2793899195.py in <module>
----> 1 model = Model(
      2     formula = 'measure_response_value ~ condition + (1 | wash_round)',
      3     priors = {'condition': 'wide'},
      4     data = data,
      5     dropna = True

~/mixed_models/bayesEnv/lib/python3.8/site-packages/bambi/models.py in __init__(self, formula, data, family, priors, link, categorical, dropna, auto_scale, default_priors, noncentered, taylor)
    162                         "Please rename the term(s) to prevent an unexpected behaviour."
    163                     )
--> 164             self._add_response(self._design.response, family, link, priors_)
    165         else:
    166             raise ValueError(

~/mixed_models/bayesEnv/lib/python3.8/site-packages/bambi/models.py in _add_response(self, response, family, link, priors)
    443                 )
    444 
--> 445         if response.refclass is not None and self.family.name != "bernoulli":
    446             raise ValueError("Index notation for response only available for 'bernoulli' family")
    447 

AttributeError: 'ResponseVector' object has no attribute 'refclass'
```

It looks weird since 
- I'm dealing with a continuous response variable
- the error I'm getting back is not the same I see in the traceback

I tested the same analysis before in a local environment with these settings and it worked just fine:
```
Last updated: Tue Aug 03 2021

Python implementation: CPython
Python version       : 3.9.5
IPython version      : 7.22.0

matplotlib: 3.4.1
numpy     : 1.20.2
arviz     : 0.11.2
bambi     : 0.5.0
pandas    : 1.2.4

Watermark: 2.2.0
```

Is there an easy workaround for this? (Unfortunately I can't change the Python version in the virtual environment I'm currently using).

**Comment by tomicapretto** [comment]
Hi @arodav, this is not a problem with Python version. The error you see is related to some mistake I committed with a new release of [formulae](https://github.com/bambinos/formulae). 

This should be fixed now. Make sure that you install Bambi version 0.5.0 and formulae version 0.1.3. Let me know if that doesn't work.

**Comment by arodav** [comment]
It works now with `formulae==0.1.3`, thanks!

**Comment by tomicapretto** [comment]
Great! Thanks for reporting the issue!

**Comment by sreedat** [comment]
@tomicapretto working with ```bambi==0.5.0``` and ```formulae==0.1.4``` and the exact same error reported above is back:. ```AttributeError: 'ResponseVector' object has no attribute 'refclass'```

Should ```bambi==0.6.0``` be used with ```formulae==0.1.4``` instead?

**Comment by tomicapretto** [comment]
@sreedat yes, use `bambi==0.6.0` and `formulae==0.1.4` please. If you want `bambi==0.5.0`, you have to downgrade `formulae` to `0.1.1`

**Comment by tomicapretto** [comment]
I recommend Bambi v0.6.0 because it includes many cool additions, but feel free to use Bambi v0.5.0 if that works for you :D

**Comment by sreedat** [comment]
@tomicapretto Thanks for getting back. I'm testing ```bambi==0.6.0``` and ```formulae==0.1.4``` and when I run the Pigs Growth model I get the following error:
```
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
C:\Users\SREEDATTA\AppData\Local\Temp/ipykernel_2420/292982306.py in <module>
----> 1 model = bmb.Model("Weight ~ Time + (Time|Pig)", data)
      2 results = model.fit()

C:\ProgramData\Anaconda3\envs\bampm3\lib\site-packages\bambi\models.py in __init__(self, formula, data, family, priors, link, categorical, dropna, auto_scale, default_priors, noncentered, taylor)
    141         data[obj_cols] = data[obj_cols].apply(lambda x: x.astype("category"))
    142 
--> 143         # Explicitly convert columns to category if desired--though this
    144         # can also be done within the formula using C().
    145         if categorical is not None:

C:\ProgramData\Anaconda3\envs\bampm3\lib\site-packages\bambi\priors.py in __init__(self, defaults, dists, terms, families)

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\ProgramData\\Anaconda3\\envs\\bampm3\\lib\\site-packages\\bambi\\config\\priors.json'
```
I went into the location indicated in the error and there is no folder called ```config``` under ```bambi```. In the entire ```bambi``` folder, when I did a search, I did not find ```priors.json```

I have already uninstalled and reinstalled ```bambi==0.6.0``` and that folder and the file are nowhere to be seen

**Comment by tomicapretto** [comment]
Is it possible you have conflicting versions? There's no `bambi/priors.py` in Bambi v0.6.0 (it's the same as the dev version you see in Github right now).

I know it may be kind of a mess. But having a new fresh environment, and doing `pip install bambi` may be worth trying. This should install Bambi v0.6.0 and all the dependencies it needs.
